### ISSUE TITLE
Possibility to install the kit from pac application install

### ISSUE THREAD

**Issue by rsantos00** [microsoft/powercat-creator-kit#117]
Would be great to have the possibility to install the CreatorKit from pac cli. When I tried in my European environment I got this error:

![image](https://user-images.githubusercontent.com/3724826/191187908-057320ba-260c-4579-ae45-6a310b1fb568.png)

Everything worked correctly when I used Admin Portal -> Open App Source -> Find the Creator.Kit and Install

**Comment by denisem-msft** [comment]
This should work now:

`pac application install --environment-id 00000000-0000-0000-0000-000000000000 --application-name CreatorKitCore`
or
`pac application install --environment https://orgname.crm.dynamics.com/ --application-name CreatorKitCore`

![image](https://user-images.githubusercontent.com/43950360/195147569-70f3e6b2-056a-4fb7-a3e9-44f070bd6e19.png)

**Comment by BrianZhangLarsen** [comment]
Still doesnt work here: 

![image](https://user-images.githubusercontent.com/32098751/205312024-d64c7088-a0ea-4cba-b61c-d6b987d87700.png)

**Comment by ronnzw** [comment]
This error still exists did anymore find a solution. My environment is in Europe.

**Comment by ronnzw** [comment]
> This error still exists did anymore find a solution. My environment is in Europe.

Never mind this. It was because of VPN
