### ISSUE TITLE
[Creator Starter Kit] BUG: icons Disappearing

### ISSUE THREAD

**Issue by 0xpaiDev** [microsoft/powercat-creator-kit#519]
![Image](https://github.com/user-attachments/assets/86095861-3156-4942-918d-fb31c2a1c01e)

Description: A few weeks ago, some users reported that icons started to disappear. As of today, this issue has escalated and now affects the majority of users. I have attempted to test the problem by using various browsers and clearing the cache, but these steps have not been successful.

Steps to Reproduce:

Open the application in any browser.
Navigate to the section where icons are supposed to be displayed.
Observe that the icons are missing.
Expected Behavior: Icons should be visible to all users across all browsers.

Actual Behavior: Icons are not visible for the majority of users, regardless of the browser used.

Additional Information:

The issue persists across different browsers.
Clearing the cache does not resolve the problem.

**Comment by trillian74** [comment]
Same situation here.

**Comment by sperry1625** [comment]
Same here.

Is anyone ever going to respond and acknowledge the issue? How about fixing
it? The silence is deafening!

Regards,

Steven Perry
***@***.***

**Comment by informiq** [comment]
I have the same problem.

Editing the application the icons appear correctly, but running the published version, they disappear.

**Comment by james-styletech** [comment]
I have experienced the same issue in all of our Apps that use the Creator Kit.
_Sometimes_ reloading the browser page makes the Icons appear again...

**Comment by james-styletech** [comment]
I had the "Icons not appearing" error this morning, so I tried to capture some more information:

Icons in the DetailsList:

![Image](https://github.com/user-attachments/assets/9aef51c0-6bc0-4a44-b24c-36b14a3971ae)

Icons in the Navigation Element:

![Image](https://github.com/user-attachments/assets/374ee9b3-fbdc-4413-809f-a7e5ff331d01)

Console errors:

![Image](https://github.com/user-attachments/assets/50c039f4-d5ad-4d65-a525-183de52c72ea)

![Image](https://github.com/user-attachments/assets/a6877ad9-cc2e-46e6-aa39-7d2ae4063c5a)

**Comment by Franco-Figueredo** [comment]
Same error here. It's been around 2-3 weeks that this error is happening withing my applications using the powercat creator kit.

**Comment by teapardee** [comment]
I have also been experiencing this issue with powercat DetailsList. It's been happening for the last few weeks. If I reload the app a few times they appear briefly. The functionality is still there, it is just an annoyance to end users. A prompt fix would be greatly appreciated!!!

**Comment by madsenfr** [comment]
For me icons don't appear on the Creator Kit Reference App, but are ok on my own app using Creator Kit.
Also, when I edit the reference app and play it, icons are ok, even if there are errors in the app.

**Comment by informiq** [comment]
I have verified that the icons are loaded in the Android client.

In Windows browsers, the icons are not displayed in any control of the Cerator Kit library.

**Comment by madsenfr** [comment]
For me even on Android the Référence app doesn't show icon, but my own app show them.

**Comment by SFSiotis** [comment]
I'm having the same issue. They appear in edit mode but not in run-time.

**Comment by phmel** [comment]
Same issue, any workaround ?

![Image](https://github.com/user-attachments/assets/0330aa1f-6e92-4b11-b8c8-f07e11b40128)

**Comment by danglotor** [comment]
Same issue as described - in navigation, command bars, icons, pivot... As reported, the functionality seems not to be broken, only the visual is very disturbing since icons are almost everywhere if you want to guide the user... 

Details: 

- only one of our tenants
- in given affected tenant all environments we could check 
- in given affected environments all apps 
- all icons it seems = whether specified manually by name, or built in the component - the navigation screenshot below shows that search is the expandable button and the arrow is built in, while the home icon is manually specified

![Image](https://github.com/user-attachments/assets/840e2f69-bed4-49c1-b26d-77f62903c37c)

In edit mode 
![Image](https://github.com/user-attachments/assets/5c155b39-8028-4791-a689-304be6bf6f05)

Published
![Image](https://github.com/user-attachments/assets/1d92fdd5-d1cc-4525-bea2-45cbf8c24a80)

**Comment by informiq** [comment]
Investigating in the browser debug console from development mode, I have found a possible cause, it seems that there is a security policy that is not allowed.

I continue investigating ...


[https://learn.microsoft.com/en-us/power-platform/admin/content-security-policy](url)

![Image](https://github.com/user-attachments/assets/8e96a89c-0303-417a-96dd-dc2ff4557a0e)

**Comment by kess-it-power** [comment]
Also getting this issue! Any updates if anyone is working on this? I'm currently working on a big project that is being held up by this issue.

**Comment by informiq** [comment]
I just found a possible solution, it's working for me!

I'm indicating the steps by translating from Spanish, it's possible that some section doesn't have the same name in another language:

1. Power Platform Administration Center
2. Environments (https://admin.powerplatform.microsoft.com/manage/environments/)
3. Select the environment on which we are going to apply the configuration
4. Configuration
5. Product
6. Privacy and security
7. Content security policy
8. Canvas
9. Configure policies: activate


Run the application. If icons are not displayed, refresh


I hope it helps you

![Image](https://github.com/user-attachments/assets/2a5e950b-4fc3-4c71-b721-78e99142af57)

**Comment by phmel** [comment]
@informiq : your config seems not working for me :-( 
It seams that icon url not working at all !
Seams same issue as https://github.com/microsoft/powercat-creator-kit/issues/514

![Image](https://github.com/user-attachments/assets/7db5c6ae-026e-4f06-807f-ce32f85f50db)

**Comment by phmel** [comment]
I have read the thread #514 and the solution that is working for me is to add a brand new command bar to the app (on default screen), set visibility to false then republish app.

**Comment by informiq** [comment]
> [@informiq](https://github.com/informiq) : your config seems not working for me :-( It seams that icon url not working at all ! Seams same issue as [#514](https://github.com/microsoft/powercat-creator-kit/issues/514)
> 


@phmel It's strange, it has worked for me in 4 different environments with two different tenants.

**Comment by danglotor** [comment]
> I have read the thread [#514](https://github.com/microsoft/powercat-creator-kit/issues/514) and the solution that is working for me is to add a brand new command bar to the app (on default screen), set visibility to false then republish app.

This solution worked for us as well! Thanks

**Comment by madsenfr** [comment]
> I have read the thread [#514](https://github.com/microsoft/powercat-creator-kit/issues/514) and the solution that is working for me is to add a brand new command bar to the app (on default screen), set visibility to false then republish app.

Thanks @phmel, it works for me too, on the reference app.

**Comment by SFSiotis** [comment]
> I have read the thread [#514](https://github.com/microsoft/powercat-creator-kit/issues/514) and the solution that is working for me is to add a brand new command bar to the app (on default screen), set visibility to false then republish app.

I tried this in our dev and it worked but it did not work in our prod environment 🫤

**Comment by teapardee** [comment]
the command bar workaround did not work for us. 

@denise-msft Can you please advise? I have clients that are asking for an update on this. Thank you.

**Comment by Raydir** [comment]
> I have read the thread [#514](https://github.com/microsoft/powercat-creator-kit/issues/514) and the solution that is working for me is to add a brand new command bar to the app (on default screen), set visibility to false then republish app.

Worked! Thanx

Edit: works only from time to time.

Problem seems to be the CDN. Can okly ve resolved 1/3 times

**Comment by cwsfcs2025** [comment]
Just chiming in like everyone else.  Same issue here.  This has been sporadically happening for several weeks.  This morning the icons displayed fine in my dev sandbox in design mode.  When playing the published app, the icons are gone...just little boxes as shown by the OP's screenshot.  I'm getting the feeling this creator kit is slowly dying on the vine as new "lite" versions of these controls are moving to public preview in Power Apps.  I love this kit...it's made my apps look sleek and professional and not like typical clunky Power Apps apps.  But the bugs are taking longer and longer to resolve, and I have to keep explaining to users that I have no control over the issue and no ETA.  That's not a sustainable situation.

**Comment by conzo937** [comment]
Hi everyone, I first tried to add an empty Fluent Command bar to the app and initially I felt it was working but then the issue returned, I then added a Fluent UI command bar with the items but still it didn’t resolve it for me. I also tried the config suggested by Informiq in this thread but that didn’t work for me either. I have noticed that it occurs for me when the power app is accessed as the first window open in a browser (it requires two refreshes to work), when the app is opened a second or third time the issue doesn’t occur. It’s like it has to of loaded and had the issue in the browser session to then work in all the other tabs if that makes sense, this is the case even if I close the first tab with our issue but keep the browser session open.

Are any of you aware how we can escalate these types or issues as it is delaying a project for me today and I’m sure many of you.

**Comment by cwsfcs2025** [comment]
I agree that it is the CDN.  An F12 in your browser will show where the fabric-icons are failing and the source domain.  And, apparently, this domain is being or has been retired:  https://build5nines.com/retirement-of-azureedge-net-dns-edg-io-business-closure-and-what-you-need-to-know/.  This source failure is affecting a ton of Microsoft resources, not just the Creator Kit since January.   Why hasn't this issue been assigned?  Please, someone on the PowerCAT team just get the correct CDN path and update these controls so the CUSTOMERS and PARTNERS can keep flying the Power Platform flag?

**Comment by teapardee** [comment]
At this point, I think everyone in this thread would appreciate, at the very least, acknowledgement of the issue. I need to be able to let my end users & clients know that this issue is being worked on. Thank you in advance.

**Comment by siladas** [comment]
Just wondering if this will require a new release of the solution.
There has been no PRs this year, which doesn't give mu hope :(.
Hopefully this won't require migrating all apps to stop using the componets, and the team will release a fix 

What version are you all using?

**Comment by Jenefer-Monroe** [comment]
Hi everyone. I've been working with the CAT team on this one, and they now have a 90% consistent repro in their tenant. 

The fix is understood at this time, but it requires a change both in the Creator Kit as well as in the product. 

Creator Kit version is local fixed, but they are awaiting the product change so that we can test it works end to end before that gets shipped. 

I don't know when the product change will be made but I understand they are highly engaged with the CAT team so everyone hope for the best on that please :)

**Comment by cwsfcs2025** [comment]
Thanks for the update @Jenefer-Monroe .  This really is a big deal even though it's just a cosmetic anomaly.  I have a project I have been working on for months that now is  postponed pending this fix.  Almost all of the client apps I have done in the last year use the kit in some way and right now all of them have UI issues because of this.  Even radio buttons in a details list are jacked up.  It's just hard to explain to clients.  A few have asked me if I am using unsupported (freeware) components in their apps...  If this isn't fixed in the next week or two I may have to eat the time and use OOTB controls to replace the kit ones.  That's a huge amount of work that I won't be able to bill.

**Comment by Jenefer-Monroe** [comment]
I hear you @cwsfcs2025 I'm in the same boat. 
It appears I'll be able to test this fix on Monday so fingers crossed and I'll let you know as soon as I know.

**Comment by denise-msft** [comment]
Hi everyone,

Apologies for the delay in getting back to you on this issue, and we appreciate your patience. We want to assure you that we’re still investigating the disappearing icons problem and understand how frustrating this can be.

We’re actively working on publishing a new version of the Creator Kit, which may help alleviate the issue. We’ll provide an update here as soon as it’s available. Thank you again for your feedback and for your continued support!

**Comment by Boreo** [comment]
Issue is still occurring on the new release.

**Comment by Raydir** [comment]
Same here...
![Image](https://github.com/user-attachments/assets/8db5ba23-cea0-4b93-b3f8-3cb10ef0c7d2)
Btw: I got the same problem with the "normal" Table Component from Microsoft...

**Comment by OvidiuGabor** [comment]
Still doesnt work..same problem after update

**Comment by Jenefer-Monroe** [comment]
Ok folks. The product fix that is requires is available finally in early release. I see it as **_3.25032.4_**
With this product change and the new creator kit build applied, I THINK THIS IS FIXED!!! 

To fix: 
- upgrade to latest creator kit 1.0.20241119.5 and apply to your app
- open your app in studio version **_3.25032.4_** or higher and republish
- refresh one million times to test. :)

Please keep me honest by going and testing it out yourself, one of the terrible things about this bug is that one might think its resolved, only to refresh one more time and see it.

**Comment by sperry1625** [comment]
@Jenefer-Monroe, @denise-msft  it is not fixed for me. Also, I do not have Studio Version `3.25032.4`. The latest version I seem to have is `3.25024.7`.

I am unable to change my Authoring Version. When I go to Settings / Support the Edit button under Authoring Version is disabled.

**Comment by Jenefer-Monroe** [comment]
Yes there is a product fix that is needed, and its only just gotten to early release. So that's required to see the fix.

You have to update your app to use the new creator kit build, and republish in product build 3.25032.4 or higher. 
But 3.25032.4 is currently just now in Early Release 

![Image](https://github.com/user-attachments/assets/bb560ddc-8597-4f14-99a7-f5f31d324822)

**Comment by eric-duncan-pdx** [comment]
@Jenefer-Monroe In the current releases for the CreatorKit Core, the version of the solution appears to be 1_0_20250310_1.  You're not proposing we revert to the older 2024 version of the solution, correct?

**Comment by sperry1625** [comment]
> Yes there is a product fix that is needed, and its only just gotten to early release. So that's required to see the fix.
> 
> You have to update your app to use the new creator kit build, and republish in product build 3.25032.4 or higher. But 3.25032.4 is currently just now in Early Release
> 
> ![Image](https://github.com/user-attachments/assets/bb560ddc-8597-4f14-99a7-f5f31d324822)

@Jenefer-Monroe , How do I change my Release Cycle from `Standard` to `Early`? When I created this environment it was not an option to select the Release Cycle.

**Comment by Jenefer-Monroe** [comment]
I dont think you can change that. I spun up a new one and put all my stuff in it. 
I use it like a second test envt to compare my new bits in combination with product new bits. 
Now that I have it, I periodically test my stuff there to see if there is anything up coming that breaks me. And also test for fixes :)

**Comment by james-styletech** [comment]
Hi @Jenefer-Monroe ,

Thank you for the update, I look forward to trying out the updated version!

@sperry1625 - As far as I know, your PowerApps "Release Plan" is entirely determined by the Region and your Environment.

Traditionally, the US Regions get the newer versions first, and other Regions follow on a few months later.
Even then, It can take Microsoft a good month or two to get the New Studio version deployed to all the tenancies in the region, so it's just pot luck as to when any given update actually hits the tenant/environment you're working in. (I work in a couple of dozen different tenancies, so it's maintenance task of its own to keep track of which tenant has which versions available!)

As for trying to get on "Early Access" releases - I'm not sure how you go about that - I've never seen that option before.

I DO however, have a cool workaround for forcing a particular Studio version (thanks to a rare _helpful_ Power Platform Developer!)

Append "&studio-version=v3.24052.30.XXXXXXXXX" to your make.powerapps.com URL.

Note that this needs a very specific _build_ number, with many decimal places.
Luckily, the same helpful developer gave me this handy resource to find out which builds are currently available:
https://authoring.us-il301.gateway.prod.island.powerapps.com/api/451f562d-fbd0-4eaf-908e-2213e0248035/healthdetail
(I hope I don't get into trouble for sharing!)

Note that Microsoft are releasing builds for several Power Apps Studio versions concurrently, so you'll need to parse the returned JSON and sort the data to get something useful like this:

Sat 08 Mar 2025 @ 00:58 - v3.25031.7.326306106
Sat 08 Mar 2025 @ 00:58 - v3.25032.4.326306378
Sat 01 Mar 2025 @ 12:53 - v3.25024.7.325648910
Sat 01 Mar 2025 @ 12:52 - v3.25031.3.325648848
Sat 22 Feb 2025 @ 18:02 - v3.25023.6.324967496
Sat 22 Feb 2025 @ 18:01 - v3.25024.6.324967598

(The above times are in GMT timezone)
Good luck everyone!

**Comment by sperry1625** [comment]
> &studio-version=v3.24052.30.XXXXXXXXX

Thank you.  I added the studio-version and that did the trick. It loaded that version and when I saved and published, the app had the icons displayed properly.

Thank you!

**Comment by Jenefer-Monroe** [comment]
Thank you so much @sperry1625 for testing! 
Please if anyone else is able to test let us know if this is resolved for you as well. Would love to put this in the past!

**Comment by Boreo** [comment]
Looks like this has fixed for me, Thanks!

**Comment by Jenefer-Monroe** [comment]
Amazing. I'm feeling very confident about this WOOHOO

**Comment by siladas** [comment]
> https://authoring.us-il301.gateway.prod.island.powerapps.com/api/451f562d-fbd0-4eaf-908e-2213e0248035/healthdetail

@james-styletech you absolute legend! thank you for that
@Jenefer-Monroe it worked for me too. I only had to re-publish the app using the version v3.25032.4.326306378.

**Comment by Jenefer-Monroe** [comment]
I think the requirement to upgrade creator kit depends on which components you were using. Some of them were already had the correct fluent pointer.
Basically the issue was that if *any* control pointed to the wrong one, then you would risk seeing the behavior.

**Comment by Daleyon** [comment]
I experienced the same issue with all apps using the toolkit across all browsers. 

All is good now after adding Fluent UI v9 Official Token sets in combination to the default example provided in the toolkit [examples](https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/theme#setting-the-theme).

Seems a bit excessive, but helped me learn 

AppTheme = {
    palette: {
        themePrimary: "#0057B7",
        themeLighterAlt: "#eff6fc",
        themeLighter: "#deecf9",
        themeLight: "#c7e0f4",
        themeTertiary: "#71afe5",
        themeSecondary: "#2b88d8",
        themeDarkAlt: "#106ebe",
        themeDark: "#005a9e",
        themeDarker: "#004578",
        neutralLighterAlt: "#faf9f8",
        neutralLighter: "#f3f2f1",
        neutralLight: "#edebe9",
        neutralQuaternaryAlt: "#e1dfdd",
        neutralQuaternary: "#d0d0d0",
        neutralTertiaryAlt: "#c8c6c4",
        neutralTertiary: "#a19f9d",
        neutralSecondary: "#605e5c",
        neutralPrimaryAlt: "#3b3a39",
        neutralPrimary: "#323130",
        neutralDark: "#201f1e",
        black: "#333333",
        white: "#ffffff"
    },
    fonts: {
        defaultFontStyle: {
            fontFamily: "'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
            fontWeight: 500
        },
        medium: { fontSize: "15px" },
        fontSize: {
            base100: "10px",
            base200: "12px",
            base300: "14px",
            base400: "16px",
            base500: "20px",
            base600: "24px",
            hero700: "28px",
            hero800: "32px",
            hero900: "40px",
            hero1000: "68px"
        },
        lineHeight: {
            base100: "14px",
            base200: "16px",
            base300: "20px",
            base400: "22px",
            base500: "28px",
            base600: "32px",
            hero700: "36px",
            hero800: "40px",
            hero900: "52px",
            hero1000: "92px"
        },
        fontFamily: {
            base: "'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
            monospace: "Consolas, 'Courier New', Courier, monospace",
            numeric: "Bahnschrift, 'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif"
        },
        fontWeight: {
            regular: 400,
            medium: 500,
            semibold: 600,
            bold: 700
        }
    },
    borderRadius: {
        borderRadiusNone: "0px",
        borderRadiusSmall: "2px",
        borderRadiusMedium: "4px",
        borderRadiusLarge: "6px",
        borderRadiusXLarge: "8px",
        borderRadiusCircular: "10000px"
    }
};

**Comment by Jaco1960** [comment]
I have installed the March version of the creator kit that should resolve this issue, but see no improvement. steps taken:
- installed new version of creator kit
- Edit application using the fluentUI detailsList (icons are displayed correctly)
- Publish the application
- Run and refresh the application
- cleared the browser cache
- run application
- Icons are displayed as generic squares

**Comment by Jenefer-Monroe** [comment]
Yes there is also a product fix that is needed, and its only just gotten to early release. So that's required to see the fix.

You have to update your app to use the new creator kit build, and republish in product build 3.25032.4 or higher. 
But 3.25032.4 is currently just now in Early Release 

![Image](https://github.com/user-attachments/assets/bb560ddc-8597-4f14-99a7-f5f31d324822)

**Comment by cwsfcs2025** [comment]
> I have installed the March version of the creator kit that should resolve this issue, but see no improvement. steps taken:
> 
> * installed new version of creator kit
> * Edit application using the fluentUI detailsList (icons are displayed correctly)
> * Publish the application
> * Run and refresh the application
> * cleared the browser cache
> * run application
> * Icons are displayed as generic squares

I must be missing something because this is not working for me at all.  When I open an affected app in studio I get a prompt that a new version is available and to click to update.  If I click, the controls are mostly unconfigured.  There must be some sub-steps that have not been explicitly documented in this thread.  It would be nice if someone could add those steps.

On your second bullet, "editing the application", what are you doing?  Are you removing each component, importing from the updated creator kit solution, reconfiguring from scratch, and then saving?  I hope this isn't actually how we have to do this.  I have these components scattered across a ton of solutions in a ton of environments.  If I have to delete and tediously reconfigure each one I will go mad because it will take several days to accomplish.  And I'll switch to OOTB controls for good.

**Comment by sperry1625** [comment]
Read the entire thread. An early release of the studio is required as well.

Regards,

Steven Perry
***@***.***

**Comment by Cofk-Cbell** [comment]
@Jaco1960  Make sure when you publish your app, your app studio version is at least 3.25032.9

![Image](https://github.com/user-attachments/assets/8dc15de5-aba8-4168-aec6-9b9f69b08791)

I was having the same issue as you but once I made sure the recommended version was selected, the icons showed up in the published app once more.

Be aware, though, that the Authoring Version available to you is dependent on the region of your environment.
https://learn.microsoft.com/en-us/power-platform/released-versions/powerapps

**Comment by pnichols77** [comment]
I installed the latest version and it totally broke the code components.

**Comment by cwsfcs2025** [comment]
> I installed the latest version and it totally broke the code components.

Same thing happened to me, which is why I asked about exact steps above.  When I updated the creator kit solution and then opened my app, Power Apps detected a new version was available and asked if I wanted to update the Creator Kit components in the app.  If you choose yes, it screws up all of the components - configurations disappear, width/height get messed up and won't reset, etc.  I found that instead of updating the creator kit, I just went into my app and chose the latest authoring version in Settings->Support and republished.  That seemed to fix it for me without doing anything with the creator kit solution whatsoever.  I'm not sure I am even going to use this kit on future projects...it's too risky IMO.  There appears to be other teams in Microsoft that make product changes that end up breaking this awesome kit.

**Comment by pnichols77** [comment]
> > I installed the latest version and it totally broke the code components.
> 
> Same thing happened to me, 

Slightly different for me. After the update any components that use icons (commandbar, fluent icon etc) shows "component loading error" and published apps with them in dont work. The versions show the old version despite the updated solution showing the new version.

I have reached the same conclusion as you as to the reliablity of these components and am pruning them out of my apps, which is a shame as the command bar with its popup menus was very easy to implement compared to alternatives for dense menu structures.

**Comment by Jenefer-Monroe** [comment]
Folks the fix requires a change from the product team and the new creator kit. 
The product change is in build 3.25032.4 or higher, something that is not yet the default build in US region until (I've been told) Monday. 

So here are the needed steps

1. Install creator kit 1.0.20241119.5 or higher to your environment
2. Wait till 3.25032.4 or higher is seen in your maker studio
3. Once its there open your app
4. Update your components to use the new creator kit. 
5. Publish

This new published version will now have the fix from the product team and the fix from the CAT team. 
Both are required.

**Comment by pnichols77** [comment]
> Folks the fix requires a change from the product team and the new creator kit. 

This doesnt help me. Im already on a later version of the creator kit, and the editor, but the code components still show version *.39 rather than the *.41 that is reported as being installed, and they show an error when I try to use them.

Ive raised this as a ticket with Microsoft support but they said I should "ask github" which suggests the support guys there dont understand what these are, and the issues I have raised here and on the code component github have so far not been acknowledged. 

This is extremely poor and would leave me advising nobody to use this kit in production apps. It's not worth the risk of things going wrong with no helpful support being available.

**Comment by james-styletech** [comment]
Hi @pnichols77 ,

We had exactly the same issue to begin with - even with the new code components installed, and the studio version updated, it just wasn't saving or updating the code components in an individual app!

After a bit of trial and error, we discovered that we needed to make a small code change, and save the app again, and then reload in the studio - then we saw the code components had updated to *.41>

1. Upload the new Creator Kit Managed Solution
2. Publish all customisations (updated controls will not show up in the studio unless they are published!)
3. Open an App that uses the creator kit
4. You should get a dialog "The Code components need updating, continue?" - Click Yes
5. (Here's where the process breaks down - simply saving/publishing/closing the app at this point will NOT update the app to use the new components)
6. Make any small edit to a piece of code (I just added a "// Update" comment to the OnStart)
7. Now Save and Publish the App
8. Close the App in the Studio
9. Re-Open the App in the Studio
10. When you now go to add a code component control - the Creator Kit controls should now say they are version *.41.

Hope that makes sense!

James.

**Comment by cwsfcs2025** [comment]
@james-styletech  Thank you for that detailed explanation and taking the time to write it up for the community. That is exactly what I had asked for earlier but was told to "read the entire thread", which didn't help.  These instructions are exactly what I needed.  I'll give this a go over the weekend.  Cheers!

**Comment by pnichols77** [comment]
> Hi [@pnichols77](https://github.com/pnichols77) ,
> 
> Hope that makes sense!
> 
> James.

It does make sense, and ive tried going through all that again, but im still left with the latest version of code components being installed

![Image](https://github.com/user-attachments/assets/25d808f2-b87c-4aec-9818-869146d2e130)

But it showing the previous version for code components when I select them in an app (even a brand new one) 

![Image](https://github.com/user-attachments/assets/f280eff9-6a73-4d04-8496-633434183d75)

And this result when I try to use one of these components

![Image](https://github.com/user-attachments/assets/ee702c8f-0ca3-4085-b954-8f7d95705dcb)


Also i appreciate im talking about code components in the creator kit github, but this one has a lot more traffic, and I think code components are a part of the creator kit? Its all the same thing, right? 

Also, I think it's significant that the only components that do work are the ones that do not use any of the icons in the CDN that prompted the update - controls like auto width label. Anything with an icon (which is most of them) result in the above.

**Comment by denise-msft** [comment]
Dear Creator Kit Users,

First and foremost, we sincerely apologize for the frustration caused by the disappearing icons issue within the Creator Starter Kit. While this issue was related to an external dependency, we understand the impact it has had on your experience, and we deeply regret the delay in addressing it.

One of the challenges we faced was the difficulty in reproducing the issue. Since it didn’t occur in a vanilla instance, the issue was escalated multiple times without being able to pinpoint the exact cause. This led to a longer resolution timeline than we would have liked, and we truly appreciate your patience as we worked through this.

We believe we’ve found a solution in the latest update, which includes improvements to the Fluent UI and other adjustments aimed at addressing the rendering inconsistencies. However, since we can’t be 100% certain that this will fully resolve the issue for all customers, we encourage you to try the following steps and let us know if the issue persists.

**Steps to try:**

1. **Confirm the app is using Power Apps Studio to the authoring version 3.25032.4 or higher:**

    Follow the steps in the documentation to validate and update if needed: https://learn.microsoft.com/power-apps/maker/canvas-apps/studio-versions

2. **Update the Creator Starter Kit:**
   - Download the latest version from the [Creator Kit GitHub Releases](https://github.com/microsoft/powercat-creator-kit/releases/latest).
   - Import the solution into your environment following the [install instructions in the documentation](https://learn.microsoft.com/power-platform/guidance/creator-kit/setup#step-1-install-the-creator-kit-solution), or reference the helpful information from other users in this thread. 

We would love to hear your feedback. If the issue is still occurring after these updates, please let us know by posting back here. We’re committed to continuing to work on a solution and will provide further assistance as needed.

Once again, we apologize for the inconvenience this has caused and thank you for your patience and understanding.

**Comment by pnichols77** [comment]
> First and foremost, we sincerely apologize for the frustration caused by the disappearing icons issue within the Creator Starter Kit. While this issue was related to an external dependency, we understand the impact it has had on your experience, and we deeply regret the delay in addressing it.

Hi - any advice for someone in my position who has updated these components, verified the install was successful, has confirmed the version of the editor being used and is left being unable to use any component that makes use of an icon (i.e. fluent icon, commandbar etc)? 

Microsoft support is unable to help and I have yet to have any acknowledgement on github of my problem. 

Are these components simply not suitable for production use?

**Comment by SFSiotis** [comment]
I waited for our environment to roll over to version 3.25032.9 (actually it made to 3.25033.8) and republished the app and now the icons are working again. I'll update the Creator Kit at some other time.
